// Generated from LCDPROTO 7d26f8ba6b8709d38b071115a025ba0dfeaefbee. Do not edit.
export const CHERRI_BRAIN_SHA = "7d26f8ba6b8709d38b071115a025ba0dfeaefbee";
export const CHERRI_MOODS = ["IDLE", "BORED", "PLAYFUL", "SLEEPY", "SHY", "AFFECTIONATE", "STARTLED", "ANNOYED", "CURIOUS", "MISCHIEF"] as const;
export const CHERRI_ACTING_CYCLES = ["NATURAL", "CUTE", "FUNNY", "HYPER", "SLEEPY", "MISCHIEF", "SHOWCASE"] as const;
export const CHERRI_INTENSITIES = ["SUBTLE", "NORMAL", "EXPRESSIVE"] as const;
export const CHERRI_SIGNATURE_IDS = ["SIG_CAUGHT_YOU_LOOKING", "SIG_BLEP_INNOCENT", "SIG_FAILED_WINK", "SIG_RASPBERRY", "SIG_PEA_SHRINK", "SIG_GIANT_PROUD_PUFF", "SIG_PANCAKE", "SIG_TALL_STRETCH", "SIG_SNEEZE_THAT_DOESNT_HAPPEN", "SIG_HAPPY_SILENT_LAUGH", "SIG_SMUG_SIDE_EYE", "SIG_SURPRISE_POP", "SIG_TONGUE_PEEK", "SIG_DOUBLE_TAKE", "SIG_PROUD_THEN_FLOP", "SIG_FAKE_SNEEZE", "SIG_HICCUP", "SIG_DANCE_CAUGHT", "SIG_OVERCONFIDENT_SPIN_FAIL", "SIG_SHADOW_ARGUMENT", "SIG_ALMOST_ASLEEP_FALL"] as const;
export const CHERRI_ACROBAT_IDS = ["SPIN_360", "BACKFLIP", "FRONTFLIP", "CARTWHEEL_LEFT", "CARTWHEEL_RIGHT"] as const;
