const fs = require("fs"),
  path = require("path"),
  ts = require("typescript");
const base = path.resolve(__dirname, "../vendor/lcdproto");
const manifest = JSON.parse(fs.readFileSync(path.join(base, "manifest.json")));
const modules = Object.keys(manifest.files)
  .filter((file) => file.endsWith(".ts"))
  .map((file) => {
    const code = ts.transpileModule(
      fs.readFileSync(path.join(base, file), "utf8"),
      {
        compilerOptions: {
          module: ts.ModuleKind.CommonJS,
          target: ts.ScriptTarget.ES2020,
        },
      },
    ).outputText;
    return `${JSON.stringify(file)}:function(require,module,exports){\n${code}\n}`;
  })
  .join(",\n");
const bundle = `var LCD=(function(){var modules={${modules}},cache={};function load(id){var key=modules[id]?id:(modules[id+'.ts']?id+'.ts':(modules[id+'/index.ts']?id+'/index.ts':id));if(cache[key])return cache[key].exports;var m=cache[key]={exports:{}};modules[key](function(p){var q=p.startsWith('@/')?p.slice(2):key.slice(0,key.lastIndexOf('/')+1)+p;var a=[];q.split('/').forEach(x=>{if(x==='..')a.pop();else if(x!=='.')a.push(x)});q=a.join('/');var r=modules[q]?q:(modules[q+'.ts']?q+'.ts':(modules[q+'/index.ts']?q+'/index.ts':q+'.ts'));return load(r);},m,m.exports);return m.exports;}return Object.assign({},${[
  "components/experimental/cloud-blob/cloudRenderer.ts",
  "components/experimental/cloud-blob/cloudLobeSystem.ts",
  "components/experimental/cloud-blob/cloudPerformance.ts",
  "lib/expressionCatalog.ts",
  "lib/characters.ts",
  "lib/blobCalibration.ts",
  "lib/blobDrag.ts",
  "lib/blobIdle.ts",
  "lib/blobBehaviour.ts",
  "lib/blobPhysics.ts",
  "lib/blobRig.ts",
  "lib/blobMind.ts",
  "lib/expressions/coreExpressions.ts",
  "lib/expressions/types.ts",
  "lib/performances/corePerformances.ts",
  "lib/performances/performanceRunner.ts",
  "lib/stateEmotionMap.ts"
].map((p) => `load(${JSON.stringify(p)})`).join(",")});})();`;
fs.writeFileSync(
  path.resolve(
    __dirname,
    "../src/components/character/canonicalRuntime.generated.ts",
  ),
  "// Generated by scripts/build-runtime.cjs. Do not edit.\nexport const canonicalRuntime = " +
    JSON.stringify(bundle) +
    ";\n",
);
// Extract unchanged pure scene/shadow drawing and floor model from pinned React layer.
const environment = fs.readFileSync(
  path.join(base, "components/states/EnvironmentLayer.tsx"),
  "utf8",
);
const helpers = environment.slice(
  environment.indexOf("const TAU"),
  environment.indexOf("export default function EnvironmentLayer"),
);
const shadow = environment.slice(
  environment.indexOf(
    "      const palette = scenePalette(displayMode);",
    environment.indexOf("const render ="),
  ),
  environment.indexOf("      const lightPulse ="),
);
const config = ts.transpileModule(
  fs.readFileSync(path.join(base, "lib/environmentConfig.ts"), "utf8"),
  {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  },
).outputText;
const envSource = `var Scene=(function(){const BODY_FRACTION=.535;${helpers}
const shadowX={current:new ScalarSpring()},shadowY={current:new ScalarSpring()},shadowHeight={current:new ScalarSpring()};
const previousFoot={current:null},cloudRef={current:true};
const staticCanvas=document.createElement('canvas');staticCanvas.width=staticCanvas.height=466;const staticCtx=staticCanvas.getContext('2d');
const background=document.createElement('canvas');background.width=background.height=466;const backgroundCtx=background.getContext('2d');
let previous=''; const exports={}; ${config} const active=exports.DEFAULT_ENVIRONMENT;
return function(ctx,currentRig,dt,time,displayMode,screenColour,isIntegrated){const delta=dt*1000;const size=466;const key=displayMode+screenColour;if(!isIntegrated&&key!==previous){drawStaticScene(staticCtx,size,displayMode,screenColour);previous=key;}
backgroundCtx.clearRect(0,0,466,466);if(!isIntegrated){backgroundCtx.drawImage(staticCanvas,0,0);}
${shadow}
if(!isIntegrated&&active.particlesEnabled)for(const mote of MOTES)drawMote(backgroundCtx,mote,time,active.particleSpeed,scenePalette(displayMode),.6);
backgroundCtx.globalAlpha=1;ctx.save();ctx.globalCompositeOperation='destination-over';ctx.drawImage(background,0,0);ctx.restore();
};})();`;
const scene = ts.transpileModule(envSource, {
  compilerOptions: { target: ts.ScriptTarget.ES2020 },
}).outputText;
fs.writeFileSync(
  path.resolve(
    __dirname,
    "../src/components/character/canonicalScene.generated.ts",
  ),
  "// Generated from pinned EnvironmentLayer.tsx.\nexport const canonicalScene = " +
    JSON.stringify(scene) +
    ";\n",
);
