const fs = require("fs"),
  path = require("path"),
  ts = require("typescript"),
  vm = require("vm");
const base = path.resolve(__dirname, "../vendor/lcdproto");
const manifest = JSON.parse(fs.readFileSync(path.join(base, "manifest.json")));
const modules = Object.keys(manifest.files)
  .filter((file) => file.endsWith(".ts"))
  .map((file) => {
    const code = ts.transpileModule(
      fs.readFileSync(path.join(base, file), "utf8"),
      {
        compilerOptions: {
          module: ts.ModuleKind.CommonJS,
          target: ts.ScriptTarget.ES2020,
        },
      },
    ).outputText;
    return `${JSON.stringify(file)}:function(require,module,exports){\n${code}\n}`;
  })
  .join(",\n");
const bundle = `var LCD=(function(){var modules={${modules}},cache={};function load(id){var key=modules[id]?id:(modules[id+'.ts']?id+'.ts':(modules[id+'/index.ts']?id+'/index.ts':id));if(cache[key])return cache[key].exports;var m=cache[key]={exports:{}};modules[key](function(p){var q=p.startsWith('@/')?p.slice(2):key.slice(0,key.lastIndexOf('/')+1)+p;var a=[];q.split('/').forEach(x=>{if(x==='..')a.pop();else if(x!=='.')a.push(x)});q=a.join('/');var r=modules[q]?q:(modules[q+'.ts']?q+'.ts':(modules[q+'/index.ts']?q+'/index.ts':q+'.ts'));return load(r);},m,m.exports);return m.exports;}return Object.assign({},${[
  "components/experimental/cloud-blob/cloudRenderer.ts",
  "components/experimental/cloud-blob/cloudLobeSystem.ts",
  "components/experimental/cloud-blob/cloudPerformance.ts",
  "components/experimental/cloud-blob/cloudMistTrails.ts",
  "lib/expressionCatalog.ts",
  "lib/characters.ts",
  "lib/blobCalibration.ts",
  "lib/blobDrag.ts",
  "lib/blobIdle.ts",
  "lib/blobBehaviour.ts",
  "lib/behaviours/controller.ts",
  "lib/behaviours/primitives.ts",
  "lib/behaviours/mouths.ts",
  "lib/mind/director.ts",
  "lib/mind/acting.ts",
  "lib/mind/emotion.ts",
  "lib/mind/catalogue/index.ts",
  "lib/orientation.ts",
  "lib/mind/cloudFacing.ts",
  "lib/mind/eventSense.ts",
  "lib/mind/types.ts",
  "lib/blobPhysics.ts",
  "lib/blobRig.ts",
  "lib/blobMind.ts",
  "lib/expressions/coreExpressions.ts",
  "lib/expressions/types.ts",
  "lib/performances/corePerformances.ts",
  "lib/performances/performanceRunner.ts",
  "lib/stateEmotionMap.ts"
].map((p) => `load(${JSON.stringify(p)})`).join(",")});})();`;
fs.writeFileSync(
  path.resolve(
    __dirname,
    "../src/components/character/canonicalRuntime.generated.ts",
  ),
  "// Generated by scripts/build-runtime.cjs. Do not edit.\nexport const canonicalRuntime = " +
    JSON.stringify(bundle) +
    ";\n",
);

// UI discovery is generated from the executable vendored exports, never from a
// second hand-maintained mobile list.
const runtimeContext = { console };
vm.runInNewContext(`${bundle}\nthis.__lcd = LCD;`, runtimeContext);
const lcd = runtimeContext.__lcd;
const stories = (lcd.ALL_STORIES || []).map((story) => ({
  id: story.id,
  category: story.category,
  rarity: story.rarity,
  durationMs: story.durationMs,
  signature: story.signature === true,
  note: story.note || "",
  silhouette: story.silhouette || "",
  mouthFamily: story.mouthFamily || "",
  actingTags: story.actingTags || [],
}));
const primitives = Object.values(lcd.PRIMITIVES || {}).map((primitive) => ({
  id: primitive.id,
  durationMs: primitive.durationMs,
  note: primitive.note,
}));
const brainSource = `// Generated from executable LCDPROTO ${manifest.sha}. Do not edit.\n` +
  `export const CHERRI_BRAIN_SHA = ${JSON.stringify(manifest.sha)} as const;\n` +
  `export const CHERRI_MOODS = ${JSON.stringify(Object.keys(lcd.MOOD_FORCE || {}))} as const;\n` +
  `export const CHERRI_ACTING_CYCLES = ${JSON.stringify(lcd.ACTING_CYCLES || [])} as const;\n` +
  `export const CHERRI_INTENSITIES = ${JSON.stringify(lcd.ACTING_INTENSITIES || [])} as const;\n` +
  `export const CHERRI_STORIES = ${JSON.stringify(stories)} as const;\n` +
  `export const CHERRI_SIGNATURE_IDS = ${JSON.stringify(stories.filter((story) => story.signature).map((story) => story.id))} as const;\n` +
  `export const CHERRI_PRIMITIVES = ${JSON.stringify(primitives)} as const;\n` +
  `export const CHERRI_ACROBAT_IDS = ${JSON.stringify(["SPIN_360", "BACKFLIP", "FRONTFLIP", "CARTWHEEL_LEFT", "CARTWHEEL_RIGHT"])} as const;\n`;
fs.writeFileSync(
  path.resolve(__dirname, "../src/domain/character/cherriBrain.generated.ts"),
  brainSource,
);

// The platform-neutral frame builder is ordinary UMD JavaScript so the exact
// same functions execute in Node parity tests and inside the WebView.
const frameCore = fs.readFileSync(
  path.resolve(__dirname, "../src/components/character/cherriFrameCore.js"),
  "utf8",
);
fs.writeFileSync(
  path.resolve(
    __dirname,
    "../src/components/character/cherriFrameCore.generated.ts",
  ),
  "// Generated by scripts/build-runtime.cjs. Do not edit.\nexport const cherriFrameCore = " +
    JSON.stringify(frameCore) +
    ";\n",
);
// Extract unchanged pure scene/shadow drawing and floor model from pinned React layer.
const environment = fs.readFileSync(
  path.join(base, "components/states/EnvironmentLayer.tsx"),
  "utf8",
);
const helpers = environment.slice(
  environment.indexOf("const TAU"),
  environment.indexOf("export default function EnvironmentLayer"),
);
const shadow = environment.slice(
  environment.indexOf(
    "      const palette = scenePalette(displayMode);",
    environment.indexOf("const render ="),
  ),
  environment.indexOf("      const lightPulse ="),
);
const config = ts.transpileModule(
  fs.readFileSync(path.join(base, "lib/environmentConfig.ts"), "utf8"),
  {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  },
).outputText;
const envSource = `var Scene=(function(){const BODY_FRACTION=.535;const composeOrientation=LCD.composeOrientation;const rotateVec3=LCD.rotateVec3;${helpers}
const shadowX={current:new ScalarSpring()},shadowY={current:new ScalarSpring()},shadowHeight={current:new ScalarSpring()};
const previousFoot={current:null},cloudRef={current:true};
const staticCanvas=document.createElement('canvas');staticCanvas.width=staticCanvas.height=466;const staticCtx=staticCanvas.getContext('2d');
const background=document.createElement('canvas');background.width=background.height=466;const backgroundCtx=background.getContext('2d');
let previous=''; const exports={}; ${config} const active=exports.DEFAULT_ENVIRONMENT;
return function(ctx,currentRig,dt,time,displayMode,screenColour,isIntegrated){const delta=dt*1000;const size=466;const key=displayMode+screenColour;if(!isIntegrated&&key!==previous){drawStaticScene(staticCtx,size,displayMode,screenColour);previous=key;}
backgroundCtx.clearRect(0,0,466,466);if(!isIntegrated){backgroundCtx.drawImage(staticCanvas,0,0);}
${shadow}
if(!isIntegrated&&active.particlesEnabled)for(const mote of MOTES)drawMote(backgroundCtx,mote,time,active.particleSpeed,scenePalette(displayMode),.6);
backgroundCtx.globalAlpha=1;ctx.save();ctx.globalCompositeOperation='destination-over';ctx.drawImage(background,0,0);ctx.restore();
};})();`;
const scene = ts.transpileModule(envSource, {
  compilerOptions: { target: ts.ScriptTarget.ES2020 },
}).outputText;
fs.writeFileSync(
  path.resolve(
    __dirname,
    "../src/components/character/canonicalScene.generated.ts",
  ),
  "// Generated from pinned EnvironmentLayer.tsx.\nexport const canonicalScene = " +
    JSON.stringify(scene) +
    ";\n",
);
